In [1]:
list1=[]
num=int(input("How many elements you want in the list?:"))

for i in range(0, num): 
    element = input()
    list1.append(element)

print('The elements in list are: ',list1)

How many elements you want in the list?:2
1
2
The elements in list are:  ['1', '2']


In [2]:
#immutable it can be changed or modified and whenever we perform any operation on it .It will make new object
s='Hi'
sl=s.lower()
print(s)
print(sl)

Hi
hi


In [3]:
#Array they are homogenous , index , order, unsorted 
#Numeric operation on array
# n dimension 
import numpy as np

In [4]:
ar=np.array([10,20,30,40,50],dtype=np.int32)
print('type array is',type(ar))
print(ar)

type array is <class 'numpy.ndarray'>
[10 20 30 40 50]


In [5]:
print('Data type of array',ar.dtype)
print('Item size of array',ar.itemsize)
print('Length of array is',len(ar))
print('Dimension of array is',ar.ndim)

Data type of array int32
Item size of array 4
Length of array is 5
Dimension of array is 1


In [6]:
ar=np.array([10,20,30,40,50],dtype=np.float32,)
print('type array is',type(ar))
print(ar)

type array is <class 'numpy.ndarray'>
[10. 20. 30. 40. 50.]


In [7]:
#arrayname[index] 
ind=int(input('enter index location'))
print('Value at given index is',ar[ind])

enter index location2
Value at given index is 30.0


In [8]:
#arrayname[index] =value it will update value at given index and if index doesnt exists it will raise error
ind=int(input('enter index location'))
value=int(input('enter value at given index'))
ar[ind]=value
print('Array after update',ar)

enter index location2
enter value at given index12
Array after update [10. 20. 12. 40. 50.]


In [9]:
#asarray()
ar1=np.asarray([100,200,300,400],dtype=np.float32)
print('type of ar1 is',type(ar1))
print(ar1)

type of ar1 is <class 'numpy.ndarray'>
[100. 200. 300. 400.]


In [10]:
print('Shape of array is',ar1.shape)

Shape of array is (4,)


In [11]:
mat1=np.asarray([[10,20,30],[40,50,60],[70,80,90]])
print(mat1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
print('Shape of array is',mat1.shape)

Shape of array is (3, 3)


In [13]:
# arrayname[rowindex][colindex]
row=int(input('enter row index'))
col=int(input('enter column index'))
print('Value at given row and column is',mat1[row][col])

enter row index1
enter column index1
Value at given row and column is 50


In [14]:
# arrayname[rowindex][colindex] =value update value at given index
mat1[1][1]=500
print(mat1)

[[ 10  20  30]
 [ 40 500  60]
 [ 70  80  90]]


In [15]:
#zeros() 
z=np.zeros((3,4),dtype=np.int32)
print('Zero matrix is \n',z)

Zero matrix is 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
o=np.ones((3,3),dtype=np.int32)
print('Ones matrix is \n',o)

Ones matrix is 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
o*7

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)

In [18]:
# full(shape , value)
n=int(input('enter number to fill '))
fmat=np.full((3,3),n)
print('Matrix is \n',fmat)

enter number to fill 6
Matrix is 
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [19]:
#identical
imat=np.eye(4,dtype=np.int32)
print('Identical matrix \n',imat)

Identical matrix 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [20]:
mat2=np.asarray([[10,20,30],[1,2,3],[100,200,300]])
print(mat2)

[[ 10  20  30]
 [  1   2   3]
 [100 200 300]]


In [21]:
mtranspose=mat2.transpose()
print('Transpose matrix is \n',mtranspose)

Transpose matrix is 
 [[ 10   1 100]
 [ 20   2 200]
 [ 30   3 300]]


In [22]:
mat2.T

array([[ 10,   1, 100],
       [ 20,   2, 200],
       [ 30,   3, 300]])

In [23]:
#arange(start, end , step) end will be excluded
arr=np.arange(10,110,step=10)
print(arr)
print(arr.shape)

[ 10  20  30  40  50  60  70  80  90 100]
(10,)


In [24]:
arr=np.arange(1,10)
print(arr)
print(arr.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [25]:
#reshape(array, new shape) it will create new array of given shape . Shape should multiple of total number of element
rarray=np.reshape(arr,(3,3))
print('Reshaped array is \n',rarray)

Reshaped array is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
rarray1=np.reshape(arr,(1,-1))
print('Reshaped array is \n',rarray1)

Reshaped array is 
 [[1 2 3 4 5 6 7 8 9]]


In [27]:
rarray2=np.reshape(arr,(-1,1))
print('Reshaped array is \n',rarray2)

Reshaped array is 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [29]:
#resize(array , new shape) create new array with given shape and element can be more or less
rearray=print('Original array is \n',arr)
np.resize(arr,(2,4))
print('Resized array is \n',rearray)

Original array is 
 [1 2 3 4 5 6 7 8 9]
Resized array is 
 None


In [30]:
print('Original array is \n',arr)
arr.shape=(3,3)
print('Reshape array is \n',arr)

Original array is 
 [1 2 3 4 5 6 7 8 9]
Reshape array is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
#ravel() create 1 d array
print('Original array is \n',arr)
print('Shape of original array is',arr.shape)
roarray=arr.ravel()
print('Shape of array after ravel',roarray.shape)
print('Array after ravel \n',roarray)
print('Dimension of array',roarray.ndim)

Original array is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of original array is (3, 3)
Shape of array after ravel (9,)
Array after ravel 
 [1 2 3 4 5 6 7 8 9]
Dimension of array 1


In [32]:
ro1array=arr.reshape((1,-1))
print(ro1array)
print(ro1array.shape)
print(ro1array.ndim)

[[1 2 3 4 5 6 7 8 9]]
(1, 9)
2


In [33]:
def user_list(l1):
  ulist=[]
  for i in range(l1):
    u=int(input("Enter your value: "))
    ulist.append(u) 
  print(ulist)

l1=int(input('Enter the size of your array :'))
user_list(l1)

Enter the size of your array :2
Enter your value: 1
Enter your value: 2
[1, 2]


In [34]:
def input_array(num=5):
    lis = []
    print("Please input the temperature in degree celsius")
    for i in range(num):
        val = float(input(f'Temperature of city {i+1} :: '))
        lis.append(val)
    return np.array(lis)
def temp_in_fahren(arr):
    return (arr*9/5) + 32
def main():
    arr = input_array(5)
    print("Temperature in Fahrenhiet\n")
    farray=temp_in_fahren(arr)
    print(farray)

In [35]:
main()

Please input the temperature in degree celsius
Temperature of city 1 :: 25
Temperature of city 2 :: 32
Temperature of city 3 :: 40
Temperature of city 4 :: 23
Temperature of city 5 :: 51
Temperature in Fahrenhiet

[ 77.   89.6 104.   73.4 123.8]


In [36]:
arr=np.arange(10,100,10)
arr=arr.reshape(3,3)
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [37]:
arr[1:2,:]

array([[40, 50, 60]])

In [38]:
arr[1: ,0:2]

array([[40, 50],
       [70, 80]])

In [39]:
arr[: ,1:2]

array([[20],
       [50],
       [80]])

In [40]:
arr[0: :2,0 ::2]

array([[10, 30],
       [70, 90]])

In [41]:
arr[2: :-2,0::2]

array([[70, 90],
       [10, 30]])

In [42]:
arr[2: :-2,2::-2]

array([[90, 70],
       [30, 10]])

In [43]:
print(arr[[0,1,2,1,0],[1,0,1,2,2]])

[20 40 80 60 30]


In [45]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [44]:
arr[arr>40]

array([50, 60, 70, 80, 90])

In [46]:
arr[arr%6==0]

array([30, 60, 90])

In [47]:
print('Max value of mat',np.max(arr))
print('Min value of mat',np.min(arr))
print('Mean value of mat',np.mean(arr))
print('Cumsum of mat', np.cumsum(arr))
print('Sum of element of mat',np.sum(arr))
print('Meadian is',np.median(arr))

Max value of mat 90
Min value of mat 10
Mean value of mat 50.0
Cumsum of mat [ 10  30  60 100 150 210 280 360 450]
Sum of element of mat 450
Meadian is 50.0


In [ ]:
arr=np.arange(1,10)
print('The array:\n',arr)

rarr=np.reshape(arr,(3,3))
print('Array after reshape:\n',rarr)#creates a new array after reshaping

rarr1=np.reshape(arr,(1,-1))
print('Array after reshape:\n',rarr1)

rarr2=np.reshape(arr,(-1,1))
print('Array after reshape:\n',rarr2)

rarr3=np.resize(arr,(2,4))
print('Array after resize:\n',rarr3)

arr.shape=(3,3)
print("Array after shape:\n",arr)#modify the original array

arr[1:2,0:]

arr[1:,0:2]

arr[::2,::2]

arr[::-2,::2]

arr[[0,1,2,1,0],[1,0,1,2,2]]#Fancy indexing

arr[arr>4]#boolean indexing

arr[arr%2==0]#boolean indexing where condition works

roarray=arr.ravel()
print('Array after ravel:\n',roarray)

arr.shape

roarray.shape

roarray.ndim

roarray1=arr.reshape(1,-1)
print(roarray1.shape)

print(roarray1.ndim)

city=5
list1=[]
for i in range(city):
    temp=float(input("Enter temperature in celsius:"))
    list1.append(temp)

temp_arr=np.array(list1)

print("The array of temperatures:",temp_arr)
print("Array Shape:",temp_arr.shape)
print("Array Dimension:",temp_arr.ndim)

def celtofar(array):
    return (array*1.8)+32

print("Temperature in fahrenheit:",celtofar(temp_arr))

print("Max value:",np.max(temp_arr))
print("Min value:",np.min(temp_arr))
print("Mean value:",np.mean(temp_arr))
print("Sum value:",np.sum(temp_arr))
print("Cumulative Sum value:",np.cumsum(temp_arr))
print("Median value:",np.median(temp_arr))