In [ ]:
d={'c1':100,'c2':200,'c3':400}
import pickle
with open('file.txt', 'wb') as fp:
  pickle.dump(d,fp) 

In [ ]:
with open('myfile.txt', 'wb') as fp:
  pickle.dump(d,fp) 

In [ ]:
with open('file.txt', 'rb') as fp:
  d1=pickle.load(fp)
print(d1)

{'c1': 100, 'c2': 200, 'c3': 400}


In [ ]:
d1

{'c1': 100, 'c2': 200, 'c3': 400}

In [2]:
import numpy as np
arr1=np.arange(10,100,10)
arr1=arr1.reshape((3,3))
arr2=np.arange(1,10)
arr2=arr2.reshape((3,3))
print('Array1 is \n',arr1)
print('Array2 is \n',arr2)

Array1 is 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Array2 is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
add=np.add(arr1,arr2)
sub=np.subtract(arr1,arr2)
mul=np.multiply(arr1,arr2)
div=np.divide(arr1,arr2)
print('Sum of array is \n',add)
print('Sub of array is \n',sub)
print('Mul of array is \n',mul)
print('Div of array is \n',div)

Sum of array is 
 [[11 22 33]
 [44 55 66]
 [77 88 99]]
Sub of array is 
 [[ 9 18 27]
 [36 45 54]
 [63 72 81]]
Mul of array is 
 [[ 10  40  90]
 [160 250 360]
 [490 640 810]]
Div of array is 
 [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [ ]:
np.exp(arr1)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26],
       [2.51543867e+30, 5.54062238e+34, 1.22040329e+39]])

In [ ]:
np.sqrt(arr1)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [ ]:
np.log(arr1)

array([[2.30258509, 2.99573227, 3.40119738],
       [3.68887945, 3.91202301, 4.09434456],
       [4.24849524, 4.38202663, 4.49980967]])

In [ ]:
arr1.dot(arr2)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [ ]:
arr3=np.arange(-3.14,3.14,0.5)
y=np.sin(arr3)
print('Sin values are \n',y)

Sin values are 
 [-0.00159265 -0.48082261 -0.84233043 -0.99760638 -0.9086335  -0.59719544
 -0.13954311  0.35227423  0.75784256  0.9778646   0.95847128  0.70441077
  0.27788593]


In [ ]:
#standard deviation
sdeviation=np.std(arr1)
print('Standard deviation is \n',sdeviation)

Standard deviation is 
 25.81988897471611


In [ ]:
#corelation cofficient
np.corrcoef(arr1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
print('Array 1 is \n',arr1)
print(arr1.shape)

Array 1 is 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


In [ ]:
print('row wise max value', np.max(arr1,axis=1))
print('row wise min value', np.min(arr1,axis=1))
print('row wise sum value', np.sum(arr1,axis=1))
print('row wise sum value', np.cumsum(arr1,axis=1))

row wise max value [30 60 90]
row wise min value [10 40 70]
row wise sum value [ 60 150 240]
row wise sum value [[ 10  30  60]
 [ 40  90 150]
 [ 70 150 240]]


In [ ]:
print('row wise max value', np.max(arr1,axis=0))
print('row wise min value', np.min(arr1,axis=0))
print('row wise sum value', np.sum(arr1,axis=0))
print('row wise sum value', np.cumsum(arr1,axis=0))

row wise max value [70 80 90]
row wise min value [10 20 30]
row wise sum value [120 150 180]
row wise sum value [[ 10  20  30]
 [ 50  70  90]
 [120 150 180]]


In [ ]:
arr1=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr1.shape

(3, 3)

In [ ]:
np.savetxt('data.txt',arr1,fmt='%.2f',header='User Data')

In [ ]:
np.loadtxt('data.txt',dtype=np.int32,skiprows=1)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]], dtype=int32)

In [ ]:
c1,c2,c3 = np.loadtxt('data.txt',dtype=np.int32,skiprows=1)
print(c1,c2,c3)

[10 20 30] [40 50 60] [70 80 90]


In [ ]:
c1,c2,c3 = np.loadtxt('data.txt',dtype=np.int32,skiprows=1,unpack=True)
print(c1,c2,c3)

[10 40 70] [20 50 80] [30 60 90]


In [ ]:
d1 = np.loadtxt('data.txt',dtype=np.int32,skiprows=1,unpack=True)
print(d1)

[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [ ]:
arr3=np.array([[10,1,30],[5,100,20],[9,80,70]])
arr3

array([[ 10,   1,  30],
       [  5, 100,  20],
       [  9,  80,  70]])

In [ ]:
arr3.sort()
print('Sorted array:\n',arr3)

Sorted array:
 [[  1  10  30]
 [  5  20 100]
 [  9  70  80]]


In [ ]:
arr3.sort(axis=0)#row wise
print('Sorted array:\n',arr3)

Sorted array:
 [[  1  10  30]
 [  5  20  80]
 [  9  70 100]]


In [ ]:
arr1=np.full((3,3),11)
arr2=np.full((3,3),5)

In [ ]:
np.vstack((arr2,arr1))

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [ 5,  5,  5],
       [11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [ ]:
np.hstack((arr2,arr1))

array([[ 5,  5,  5, 11, 11, 11],
       [ 5,  5,  5, 11, 11, 11],
       [ 5,  5,  5, 11, 11, 11]])

In [ ]:
np.r_[arr2,arr1]

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [ 5,  5,  5],
       [11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [ ]:
np.row_stack((arr2,arr1))

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [ 5,  5,  5],
       [11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [ ]:
np.column_stack((arr2,arr1))

array([[ 5,  5,  5, 11, 11, 11],
       [ 5,  5,  5, 11, 11, 11],
       [ 5,  5,  5, 11, 11, 11]])

In [ ]:
np.concatenate((arr1,arr2),axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
np.concatenate((arr1,arr2),axis=1)

array([[10, 20, 30,  1,  2,  3],
       [40, 50, 60,  4,  5,  6],
       [70, 80, 90,  7,  8,  9]])

In [ ]:
np.append(arr1,arr2)

array([10, 20, 30, 40, 50, 60, 70, 80, 90,  1,  2,  3,  4,  5,  6,  7,  8,
        9])

In [ ]:
np.append(arr1,arr2,axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
np.append(arr1,arr2,axis=1)

array([[10, 20, 30,  1,  2,  3],
       [40, 50, 60,  4,  5,  6],
       [70, 80, 90,  7,  8,  9]])

In [ ]:
arr5=np.arange(100,400,100)
np.append(arr1,arr5)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 200, 300])

In [ ]:
np.insert(arr1,1,arr5)

array([ 10, 100, 200, 300,  20,  30,  40,  50,  60,  70,  80,  90])

In [ ]:
np.insert(arr1,1,arr2,axis=0)

array([[10, 20, 30],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arrinsert=np.insert(arr1,1,arr2,axis=1)
arrinsert

array([[10,  1,  4,  7, 20, 30],
       [40,  2,  5,  8, 50, 60],
       [70,  3,  6,  9, 80, 90]])

In [ ]:
np.delete(arrinsert,1,axis=1)

array([[10,  4,  7, 20, 30],
       [40,  5,  8, 50, 60],
       [70,  6,  9, 80, 90]])

In [ ]:
np.delete(arrinsert,2,axis=0)

array([[10,  1,  4,  7, 20, 30],
       [40,  2,  5,  8, 50, 60]])

In [ ]:
arr1=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2=np.arange(100,400,100)

In [ ]:
arr1,arr2

(array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]), array([100, 200, 300]))

In [ ]:
arr1+arr2

array([[110, 220, 330],
       [140, 250, 360],
       [170, 280, 390]])

In [ ]:
arr3=np.full((2,2),7)
arr3

array([[7, 7],
       [7, 7]])

In [ ]:
r1,r2,r3=np.vsplit(arr1,3)
print('Row 1 is ',r1)
print('Row 2 is',r2)
print('Row 3 is ',r3)

Row 1 is  [[10 20 30]]
Row 2 is [[40 50 60]]
Row 3 is  [[70 80 90]]


In [ ]:
c1,c2,c3=np.hsplit(arr1,3)
print('Column 1 is ',c1)
print('Column 2 is',c2)
print('Column 3 is ',c3)

Column 1 is  [[10]
 [40]
 [70]]
Column 2 is [[20]
 [50]
 [80]]
Column 3 is  [[30]
 [60]
 [90]]


In [1]:
import pandas as pd

In [ ]:
s1=pd.Series([10,20,30,40,50])
print('Type of s1',type(s1))
print('Series is \n',s1)

Type of s1 <class 'pandas.core.series.Series'>
Series is 
 0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
s1=pd.Series([10,20,30,40,50],index=[101,201,301,401,501])
print('Type of s1',type(s1))
print('Series is \n',s1)

Type of s1 <class 'pandas.core.series.Series'>
Series is 
 101    10
201    20
301    30
401    40
501    50
dtype: int64


In [ ]:
s2=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])

In [ ]:
type(s2)

pandas.core.series.Series

In [ ]:
s2

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
#value at label
s2['c']

30

In [ ]:
#value at index
s2[3]

40

In [ ]:
# value from series can be access with help of index if labels are alphabetic or alpha numeric 
s1[101]

10

In [ ]:
#seriesname[label]=value update value for given label and if label not exists it  will add new value to the series 

ln=input('enter label ')
v=int(input('enter value for label'))
print('Series before update \n',s2)
s2[ln]=v
print('Series after update is \n',s2)

enter label 4
enter value for label21
Series before update 
 a    10
b    20
c    30
d    40
e    50
dtype: int64
Series after update is 
 a    10
b    20
c    30
d    40
e    50
4    21
dtype: int64


In [ ]:
print('max value:',max(s2))

max value: 60


In [ ]:
print('min value:',min(s2))

min value: 10


In [ ]:
print('sum value:',sum(s2))

sum value: 180


In [ ]:
print('length:',len(s2))

length: 5


In [ ]:
print('median value:',np.median(s2))

median value: 40.0


In [ ]:
s2['a':'e']

a    10
b    20
c    60
d    40
e    50
dtype: int64

In [ ]:
s2[0:4]

a    10
b    20
c    60
d    40
dtype: int64

In [ ]:
s2.loc['a':'t':2]

a    10
c    60
e    50
dtype: int64

In [ ]:
s2['a': : 2]

a    10
c    30
e    50
dtype: int64

In [ ]:
#loc[startlabel:endlabel:step] do slicing on basis of labels
s1.loc[501: :-2 ]

501    50
301    30
101    10
dtype: int64

In [ ]:
#iloc[startindex : endindex:step] do slicing on basis of index
s1.iloc[0:4]

101    10
201    20
301    30
401    40
dtype: int64

In [ ]:
s3=pd.Series(d)

In [ ]:
s3

c1    100
c2    200
c3    400
dtype: int64

In [3]:
df=pd.DataFrame([[10,20,30],[40,50,60],[70,80,90]],index=[2000,2010,2020],columns=['hp','dell','lenevo'])
df

hp  dell  lenevo
2000  10    20      30
2010  40    50      60
2020  70    80      90

In [4]:
#dataframe[columname]
df['dell']

2000    20
2010    50
2020    80
Name: dell, dtype: int64

In [5]:
#dataframename.ColumnName
df.hp

2000    10
2010    40
2020    70
Name: hp, dtype: int64

In [6]:
#dataframe[columname][rowlabel]
df['dell'][2010]

50

In [7]:
# dataframe.loc[rowlabelstart:rowlabelend:step , columnlabelstart : columnlabelend:step]
df.loc[2010:2010 , :]

hp  dell  lenevo
2010  40    50      60

In [8]:
df.loc[: ,'hp': :2]

hp  lenevo
2000  10      30
2010  40      60
2020  70      90

In [9]:
df.iloc[: ,0: :2]

hp  lenevo
2000  10      30
2010  40      60
2020  70      90

In [10]:
df.iloc[1:2,:]

hp  dell  lenevo
2010  40    50      60

In [11]:
d={'hp':[200,300,400,500],'dell':[400,600,800,900],'sony':[500,600,70,80]}
df=pd.DataFrame(d,index=[2005,2010,2015,2020])
df['lenevo']=[200,500,800,900]
df

hp  dell  sony  lenevo
2005  200   400   500     200
2010  300   600   600     500
2015  400   800    70     800
2020  500   900    80     900

In [25]:
from google.colab import files
uploaded=files.upload()

Saving Pokemon.csv to Pokemon.csv


In [26]:
import pandas as pd
df_pokemon=pd.read_csv('Pokemon.csv')

In [27]:
df_pokemon.head()

#                   Name  Type1  ... Speed  Generation  Legendary
0  1              Bulbasaur  Grass  ...    45           1      False
1  2                Ivysaur  Grass  ...    60           1      False
2  3               Venusaur  Grass  ...    80           1      False
3  3  VenusaurMega Venusaur  Grass  ...    80           1      False
4  4             Charmander   Fire  ...    65           1      False

[5 rows x 13 columns]

In [28]:
df_pokemon.shape

(800, 13)

In [29]:
df_pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   #           800 non-null    int64 
 1   Name        800 non-null    object
 2   Type1       800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64 
 5   HP          800 non-null    int64 
 6   Attack      800 non-null    int64 
 7   Defense     800 non-null    int64 
 8   Sp. Atk     800 non-null    int64 
 9   Sp. Def     800 non-null    int64 
 10  Speed       800 non-null    int64 
 11  Generation  800 non-null    int64 
 12  Legendary   800 non-null    bool  
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB


In [30]:
df_pokemon['Type1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [31]:
df_pokemon.dropna(inplace=True)
df_pokemon

#                   Name    Type1  ... Speed  Generation  Legendary
0      1              Bulbasaur    Grass  ...    45           1      False
1      2                Ivysaur    Grass  ...    60           1      False
2      3               Venusaur    Grass  ...    80           1      False
3      3  VenusaurMega Venusaur    Grass  ...    80           1      False
6      6              Charizard     Fire  ...   100           1      False
..   ...                    ...      ...  ...   ...         ...        ...
795  719                Diancie     Rock  ...    50           6       True
796  719    DiancieMega Diancie     Rock  ...   110           6       True
797  720    HoopaHoopa Confined  Psychic  ...    70           6       True
798  720     HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721              Volcanion     Fire  ...    70           6       True

[414 rows x 13 columns]

In [ ]:
df_pokemon=df_pokemon.drop(columns=['Type 2'])

In [12]:
from sklearn.datasets import load_iris
fdata=load_iris()
fdata

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [13]:
fdata.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [14]:
df_flower=pd.DataFrame(fdata['data'],columns=fdata['feature_names'])
df_flower['flower category']=fdata['target']
df_flower

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower category
0                  5.1               3.5  ...               0.2                0
1                  4.9               3.0  ...               0.2                0
2                  4.7               3.2  ...               0.2                0
3                  4.6               3.1  ...               0.2                0
4                  5.0               3.6  ...               0.2                0
..                 ...               ...  ...               ...              ...
145                6.7               3.0  ...               2.3                2
146                6.3               2.5  ...               1.9                2
147                6.5               3.0  ...               2.0                2
148                6.2               3.4  ...               2.3                2
149                5.9               3.0  ...               1.8                2

[150 rows x 5 columns]

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower category
0                5.1               3.5  ...               0.2                0
1                4.9               3.0  ...               0.2                0
2                4.7               3.2  ...               0.2                0
3                4.6               3.1  ...               0.2                0
4                5.0               3.6  ...               0.2                0

[5 rows x 5 columns]

In [16]:
df_flower.head() # display top 5 data 

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower category
0                5.1               3.5  ...               0.2                0
1                4.9               3.0  ...               0.2                0
2                4.7               3.2  ...               0.2                0
3                4.6               3.1  ...               0.2                0
4                5.0               3.6  ...               0.2                0

[5 rows x 5 columns]

In [17]:
df_flower.head(10)

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower category
0                5.1               3.5  ...               0.2                0
1                4.9               3.0  ...               0.2                0
2                4.7               3.2  ...               0.2                0
3                4.6               3.1  ...               0.2                0
4                5.0               3.6  ...               0.2                0
5                5.4               3.9  ...               0.4                0
6                4.6               3.4  ...               0.3                0
7                5.0               3.4  ...               0.2                0
8                4.4               2.9  ...               0.2                0
9                4.9               3.1  ...               0.1                0

[10 rows x 5 columns]

In [18]:
df_flower.tail() # display last 5 data

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower category
145                6.7               3.0  ...               2.3                2
146                6.3               2.5  ...               1.9                2
147                6.5               3.0  ...               2.0                2
148                6.2               3.4  ...               2.3                2
149                5.9               3.0  ...               1.8                2

[5 rows x 5 columns]

In [19]:
df_flower.shape

(150, 5)

In [20]:
df_flower.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'flower category'],
      dtype='object')

In [21]:
df_flower.count()

sepal length (cm)    150
sepal width (cm)     150
petal length (cm)    150
petal width (cm)     150
flower category      150
dtype: int64

In [22]:
df_flower.index

RangeIndex(start=0, stop=150, step=1)

In [23]:
df_flower.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   flower category    150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [24]:
df_flower.describe()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower category
count         150.000000        150.000000  ...        150.000000       150.000000
mean            5.843333          3.057333  ...          1.199333         1.000000
std             0.828066          0.435866  ...          0.762238         0.819232
min             4.300000          2.000000  ...          0.100000         0.000000
25%             5.100000          2.800000  ...          0.300000         0.000000
50%             5.800000          3.000000  ...          1.300000         1.000000
75%             6.400000          3.300000  ...          1.800000         2.000000
max             7.900000          4.400000  ...          2.500000         2.000000

[8 rows x 5 columns]